planner_config_file: "configs/planner.yaml"
dune_checkpoint: "example/model/diff_robot_default/model_5000.pth"

refresh_initial_path: False
flip_angle: False
include_initial_path_direction: False

frame:
  map: "map"
  base: "base_link"
  lidar: "lidar"

topic:
  scan: "/scan"
  cmd_vel: "/cmd_vel"

scan_range: [0.3, 10.0]
scan_angle: [-3.14, 3.14]
scan_downsample: 1
marker_size: 0.05
marker_z: 0.3

